# Generated by Django 5.0.2 on 2024-05-15 13:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_definition", models.TextField(default='""')),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 5, 15, 13, 6, 41, 537274)
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
                "db_table": "report_definition",
            },
        ),
        migrations.CreateModel(
            name="ReportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=36)),
                ("report_definition", models.TextField()),
                ("data", models.TextField()),
                ("is_test_data", models.BooleanField()),
                ("pdf_file", models.BinaryField(null=True)),
                ("pdf_file_size", models.IntegerField(null=True)),
                ("created_on", models.DateTimeField()),
            ],
            options={
                "db_table": "report_request",
            },
        ),
    ]
